/**
 * 疾病详情中文化：保留常用影像/骨科缩写，其余英文尽量译为中文。
 */
import { GENERAL_PHRASES, GENERAL_WORDS } from './general-en-zh.mjs';
import { EXTRA_PHRASES, EXTRA_WORDS } from './general-en-zh-extra.mjs';
import { BULK_PHRASES, BULK_WORDS, BULK_KEEP_LOWER } from './en-zh-bulk.mjs';
import { ABBREV_GLOSS_UNIQUE } from './abbrev-zh.mjs';
import { collapseNestedGloss } from '../data/abbrev-fix.mjs';

export const KEEP_UPPER = new Set([
  'MRI', 'CT', 'US', 'HU', 'T1', 'T2', 'STIR', 'GRE', 'SWI', 'PD', 'FS',
  'ACL', 'PCL', 'MCL', 'LCL', 'DRUJ', 'TFCC', 'IOM', 'SLAP', 'LHB',
  'OPLL', 'OLF', 'TGCT', 'PVNS', 'WDLPS', 'ALT', 'SFT', 'HPC', 'OCD', 'OCI',
  'DISH', 'RA', 'OA', 'AVN', 'GCT', 'ABC', 'UBC', 'FD', 'HME', 'MAS', 'AS',
  'NSAID', 'ORIF', 'TEA', 'TSA', 'RSA', 'GNAS', 'NF1', 'MPNST', 'HPT', 'ESR',
  'CRP', 'DEXA', 'FRAX', 'DECT', 'MRA', 'PAO', 'ICRS', 'AJCC', 'WHO', 'STAT6',
  'CD34', 'CECS', 'RICE', 'PT', 'TKA', 'HALO', 'VAI', 'ADI', 'PADI', 'TLICS',
  'PLC', 'RTI', 'FOOSH', 'SNAC', 'KL', 'GH', 'AC', 'CC', 'MFC', 'LFC', 'PIP',
  'DIP', 'MCP', 'CPPD', 'TOPH', 'SONK', 'SIFK', 'BME', 'DISI', 'VISI', 'SLAC',
  'CTA', 'HAGL', 'ALPSA', 'MDI', 'DFSP', 'ASPS', 'EWSR1', 'SS18', 'IVDU',
  'TB', 'OM', 'CRMO', 'SAPHO', 'SPA', 'TNF', 'DMARD', 'EMG', 'PET', 'SPECT',
  'AKI', 'CK', 'DVT', 'OR', 'ICU', 'UK', 'FHL', 'FAI', 'FADIR', 'VMO', 'TT',
  'MACI', 'TTO', 'TT', 'TG', 'CECS', 'MACI', 'VMO', 'FADIR', 'CAM', 'PSA',
  'ALP', 'CMC', 'CSF', 'ONFH', 'NOF', 'SBP', 'OFD', 'DWI', 'DDH', 'MFH', 'APL',
  'FAP', 'SCFE', 'LCH', 'NNIS', 'VIT', 'LCEA', 'SPONK', 'SCIF', 'SSX', 'UPS',
  'MODIC', 'CHIARI', 'EWING', 'MASON', 'BANKART', 'HAWKINS', 'SEGOND', 'KELLGREN',
  'SCHMORL', 'LISFRANC', 'SCHATZKER', 'WEBER', 'BRODIE', 'ROCKWOOD', 'GARDEN',
  'SANDERS', 'JEFFERSON', 'MONTEGGIA', 'NEER', 'PAGET', 'MAFFUCCI', 'SCHEUERMANN',
  'MAISONNEUVE', 'ESSEX', 'LOPRESTI', 'ENNEKING', 'MAZABRAUD', 'GOUTALLIER',
  'DUPUYTREN', 'OLLIER', 'GARDNER', 'STAT', 'CORD', 'PIVOT', 'FADIR', 'MACI',
  'NSAIDS', 'MACI', 'BERNDT', 'HARTY', 'OUTERBRIDGE', 'MERCHANT', 'SKYLINE',
  'PEDOWITZ', 'PERONEAL', 'DONOGHUE', 'LACHMAN', 'HAGLUND', 'KLEIN', 'PERTHES',
  'CATTERALL', 'CAPANNA', 'ADAMANTINOMA', 'BUSCHKE', 'OLLENDORFF', 'SHEPHERD',
  'CROOK', 'BENNETT', 'HANGMAN', 'LEVINE', 'CHANCE', 'FAP', 'HORNBLOWER',
  'MULDER', 'MEYERDING', 'LAWRENCE', 'CODMAN', 'VALSALVA', 'BOUCHARD', 'HEBERDEN',
  'LOOSER', 'MCCUNE', 'ALBRIGHT', 'LANGENSKIOLD', 'ROCKWOOD', 'ZANCA', 'BAR',
  'LERI', 'WEILL', 'VICKERS', 'WRISBERG', 'KASABACH', 'MERRITT', 'MORTON',
  'MADELUNG', 'KIENBOCK', 'PREISER', 'SNAC', 'SLAC', 'DISI', 'VISI', 'HNP',
  'III', 'II', 'IV', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII',
  'MCAS', 'BRAF', 'BRACHYURY', 'EGFR', 'IDH', 'USP', 'USP6', 'PBL', 'CRAB', 'SMM',
  'MAP', 'CHOP', 'RCHOP', 'HUVOS', 'BASDAI', 'BASMI', 'MSASSS', 'ASAS', 'ACR', 'EULAR',
  'DAS28', 'SHARP', 'ORTOLANI', 'BARLOW', 'GRAF', 'IHDI', 'MYERSON', 'HARDCASTLE',
  'SCHIZAS', 'CASPAR', 'LODER', 'SOUTHWICK', 'HERRING', 'MIREL', 'BILSKY', 'ISS',
  'DURIE', 'SALMON', 'BURGESS', 'TILE', 'ALLMAN', 'ROBINSON', 'BOHLER', 'GISSANE',
  'ARCO', 'FICAT', 'MCMURRAY', 'APLEY', 'COLLES', 'SMITH', 'BARTON', 'LAUGE', 'HANSEN',
  'DANIS', 'HERBERT', 'RUSSE', 'CIERNY', 'MADER', 'MRC', 'JOBE', 'TINEL', 'ANTONI',
  'LISCH', 'BROOKER', 'MILGRAM', 'LANGERHANS', 'JAFFE', 'LICHTENSTEIN', 'CAMPANACCI',
  'LEDERHOSE', 'LEDDERHOSE', 'HOMAN', 'DOPPLER', 'NORDIC', 'NF1', 'ANN', 'ARBOR',
  'HODGKIN', 'NHL', 'LEGG', 'CALVE', 'CALV', 'WALDENSTROM', 'WALDENSTR', 'GALEAZZI',
  'POTT', 'APC', 'AHLBACK', 'SHENTON', 'HOA', 'DMARDS', 'HLA', 'TFE', 'IHC', 'LPS',
  'PLL', 'EDWARDS', 'ANDERSON', 'HAMADA', 'BAKER', 'PROTUBERANS', 'CATENIN', 'EWSR',
  'PTH', 'LDL', 'MORQUIO', 'BLount', 'LACERTUS', 'GRASS', 'ROLANDO', 'SPENCE',
  'SEATBELT', 'GARTLAND', 'BAUMANN', 'HILL', 'SACHS', 'GULL', 'WING', 'CRAB',
  'CANALE', 'DEDIFF', 'ODONTOIDEUM', 'DESMOID', 'PARS', 'HLER', 'HURLER', 'CHARCOT',
  'POlKA', 'DOT', 'CORDUROY', 'SUNBURST', 'CODMAN', 'OFD', 'LGC', 'SBP', 'MM', 'MO',
  'NOF', 'ABC', 'FD', 'GCT', 'TGCT', 'PVNS', 'WDLPS', 'ALT', 'SFT', 'HPC', 'OCD',
  'OCI', 'DISH', 'RA', 'OA', 'AVN', 'TEA', 'TSA', 'RSA', 'GNAS', 'MPNST', 'AJCC',
  'WHO', 'STAT6', 'CD34', 'RICE', 'TKA', 'HALO', 'VAI', 'ADI', 'PADI', 'TLICS',
  'PLC', 'RTI', 'FOOSH', 'SNAC', 'KL', 'GH', 'CC', 'MFC', 'LFC', 'CPPD', 'TOPH',
  'SONK', 'SIFK', 'BME', 'SLAC', 'CTA', 'HAGL', 'ALPSA', 'MDI', 'DFSP', 'ASPS',
  'SS18', 'IVDU', 'TB', 'OM', 'CRMO', 'SAPHO', 'SPA', 'TNF', 'EMG', 'PET', 'SPECT',
  'AP', 'PA', 'CM', 'RF', 'LD', 'CE', 'PF', 'FH', 'AO', 'OP', 'SL', 'CA', 'HE', 'CS',
  'LL', 'PM', 'IP', 'ECU', 'EIP', 'HTO', 'SLJ', 'CAD', 'HS', 'WBC', 'CCP', 'B3', 'THA',
  'RCT', 'UKA', 'ACI', 'CRPS', 'DHS', 'TNM', 'LC', 'HA', 'QCT', 'VITD', 'SHOX', 'SGHL',
  'CHL', 'AHLB', 'OH', 'M3', 'M4', 'R0', 'IIA', 'IIB', 'LF', 'PEC', 'RE', 'VS', 'UP',
  'EN', 'MOD', 'WER', 'GY', 'IDS', 'AKP', 'CPP', 'MTP', 'MGHL', 'ABER', 'PLIF', 'TLIF',
  'ALIF', 'ACDF', 'BMI', 'VHL', 'UOP', 'TKI', 'LDH', 'HPF', 'EMA', 'AFP', 'IFN', 'MDM2',
  'CDK4', 'PDGFR', 'FNCLCC', 'TFE3', 'ERG', 'CD31', 'CCCS', 'LGC', 'UCL', 'RCL', 'FX',
  'CN', 'MRSA', 'SLE', 'PD', 'FS', 'TT', 'TG', 'EXT1', 'EXT2', 'CSF1', 'R0', 'MOHS',
  'TFE3', 'EICess', 'EDI', 'ALLG', 'MHE', 'P53', 'AVM', 'ISSVA', 'PET-CT', 'TT-TG',
  'HLA', 'B27', 'IGF', 'IL', 'R-ISS', 'R-CHOP', 'V600E', 'S-100', 'Q12', 'Q6H', 'T90',
  'OK-432', 'T-CELL', 'LDL-C', 'MMHG', 'EURO-EWING', 'COL1A1', 'PDGFB', 'EWSR1', 'FLI1',
  'NAB2', 'STAT6', 'MYH9', 'USP6', 'FUS', 'DDIT3', 'ASPSCR1', 'TFE3', 'SS18-SSX', 'I-IV',
  'T12', 'T8', 'T9', 'T12-L1', 'PD-FS', 'LGc-OS', 'LGc', 'OS', 'MR', 'FAST', 'VEST',
  'DENS', 'BLOC', 'SITU', 'ASIA', 'RADIALHEAD', 'WEST', 'POINT', 'X-RAY', 'XRAY'
]);

const PHRASES_RAW = [
  ['musculotendinous junction', '肌腱结合部'],
  ['rectus femoris', '股直肌'],
  ['biceps femoris', '股二头肌'],
  ['gastrocnemius', '腓肠肌'],
  ['volar plate', '掌侧板'],
  ['central slip', '中央束'],
  ['mallet finger', '槌状指'],
  ["Morton's neuroma", 'Morton 神经瘤'],
  ['Morton neuroma', 'Morton 神经瘤'],
  ['os trigonum', '距后三角骨'],
  ['shin splints', '胫骨应力综合征'],
  ['stress fracture', '应力性骨折'],
  ['bone marrow edema', '骨髓水肿'],
  ['fatty atrophy', '脂肪萎缩'],
  ['familial hypercholesterolemia', '家族性高胆固醇血症'],
  ['compartment syndrome', '骨筋膜室综合征'],
  ['chronic exertional compartment syndrome', '慢性劳力性骨筋膜室综合征'],
  ['myositis ossificans', '骨化性肌炎'],
  ['nodular fasciitis', '结节性筋膜炎'],
  ['plantar fibromatosis', '足底纤维瘤病'],
  ['synovial sarcoma', '滑膜肉瘤'],
  ['well-differentiated liposarcoma', '高分化脂肪肉瘤'],
  ['atypical lipomatous tumor', '非典型性脂肪瘤'],
  ['myxoid liposarcoma', '黏液样脂肪肉瘤'],
  ['dermatofibrosarcoma protuberans', '隆突性皮肤纤维肉瘤'],
  ['solitary fibrous tumor', '孤立性纤维性肿瘤'],
  ['hemangiopericytoma', '血管外皮细胞瘤'],
  ['pigmented villonodular synovitis', '色素沉着绒毛结节性滑膜炎'],
  ['tenosynovial giant cell tumor', '腱鞘巨细胞瘤'],
  ['erosive osteoarthritis', '侵蚀性骨关节炎'],
  ['Charcot arthropathy', 'Charcot 神经关节病'],
  ['Charcot joint', 'Charcot 关节病'],
  ['subchondral insufficiency fracture', '软骨下功能不全骨折'],
  ['transient osteoporosis', '短暂性骨质疏松'],
  ['osteochondritis dissecans', '剥脱性骨软骨炎'],
  ['disc herniation', '椎间盘突出'],
  ['disc protrusion', '椎间盘突出'],
  ['spinal cord', '脊髓'],
  ['nerve root', '神经根'],
  ['facet joint', '小关节'],
  ['synovial cyst', '滑膜囊肿'],
  ['epidural abscess', '硬膜外脓肿'],
  ['Schmorl node', 'Schmorl 结节'],
  ['Modic change', 'Modic 终板改变'],
  ['posterior longitudinal ligament', '后纵韧带'],
  ['ligamentum flavum', '黄韧带'],
  ['acetabular dysplasia', '髋臼发育不良'],
  ['hip labral tear', '髋臼盂唇撕裂'],
  ['patellofemoral pain', '髌股关节疼痛'],
  ['meniscal cyst', '半月板囊肿'],
  ['discoid meniscus', '盘状半月板'],
  ['loose bodies', '游离体'],
  ['loose body', '游离体'],
  ["Baker's cyst", '腘窝囊肿'],
  ['Baker cyst', '腘窝囊肿'],
  ['synovial chondromatosis', '滑膜软骨瘤病'],
  ['bench press', '卧推'],
  ['Popeye deformity', '大力水手征'],
  ['external rotation', '外旋'],
  ['internal rotation', '内旋'],
  ['passive stretch', '被动牵拉'],
  ['return to sport', '重返运动'],
  ['flow voids', '流空信号'],
  ['split-fat sign', '脂肪分隔征'],
  ['enter-exit sign', '进出神经征'],
  ['target sign', '靶征'],
  ['ring-and-arc', '环弧状'],
  ['ground-glass', '磨玻璃样'],
  ['soap bubble', '皂泡样'],
  ['double line sign', '双线征'],
  ['fluid-fluid level', '液-液平'],
  ['pathologic fracture', '病理性骨折'],
  ['stress reaction', '应力反应'],
  ['weight bearing', '负重位'],
  ['bone scan', '骨扫描'],
  ['core decompression', '髓芯减压'],
  ['wide excision', '广泛切除'],
  ['bone graft', '植骨'],
  ['internal fixation', '内固定'],
  ['closed reduction', '闭合复位'],
  ['open reduction', '开放复位'],
  ['rotator cuff', '肩袖'],
  ['post-traumatic', '创伤后'],
  ['post traumatic', '创伤后'],
  ['high energy', '高能量'],
  ['low energy', '低能量'],
  ['range of motion', '活动范围'],
  ['soft tissue', '软组织'],
  ['bone destruction', '骨破坏'],
  ['cortical breach', '皮质突破'],
  ['periosteal reaction', '骨膜反应'],
  ['joint space', '关节间隙'],
  ['joint effusion', '关节积液'],
  ['intra-articular', '关节内'],
  ['extra-articular', '关节外'],
  ['Clinical Pearls', '临床要点'],
  ['subscapularis', '肩胛下肌'],
  ['infraspinatus', '冈下肌'],
  ['teres minor', '小圆肌'],
  ['supraspinatus', '冈上肌'],
  ['pectoralis major', '胸大肌'],
  ['gluteus medius', '臀中肌'],
  ['gluteus minimus', '臀小肌'],
  ['adductor longus', '长收肌'],
  ['quadriceps', '股四头肌'],
  ['hamstring', '腘绳肌'],
  ['schwannoma', '神经鞘瘤'],
  ['neurofibroma', '神经纤维瘤'],
  ['hemangioma', '血管瘤'],
  ['lymphangioma', '淋巴管瘤'],
  ['ganglion cyst', '腱鞘囊肿'],
  ['liposarcoma', '脂肪肉瘤'],
  ['chondromalacia', '软骨软化'],
  ['patellofemoral', '髌股'],
  ['spondylolysis', '椎弓峡部裂'],
  ['spondylolisthesis', '椎体滑脱'],
  ['weightlifting', '举重'],
  ['hyperextension', '过伸'],
  ['hypervascular', '富血供'],
  ['hyperechoic', '高回声'],
  ['hypoechoic', '低回声'],
  ['hyperintense', '高信号'],
  ['hypointense', '低信号'],
  ['enhancement', '强化'],
  ['calcification', '钙化'],
  ['ossification', '骨化'],
  ['heterogeneous', '不均匀'],
  ['homogeneous', '均匀'],
  ['infiltrative', '浸润性'],
  ['expansile', '膨胀性'],
  ['postoperative', '术后'],
  ['preoperative', '术前'],
  ['postmenopausal', '绝经后'],
  ['middle-aged', '中年'],
  ['young adult', '青年'],
  ['adolescent', '青少年'],
  ['elderly', '老年'],
  ['pediatric', '儿童'],
  ['traumatic', '创伤性'],
  ['progressive', '进行性'],
  ['subacute', '亚急性'],
  ['bilateral', '双侧'],
  ['unilateral', '单侧'],
  ['symmetric', '对称'],
  ['asymmetric', '不对称'],
  ['proximal', '近端'],
  ['distal', '远端'],
  ['anterior', '前'],
  ['posterior', '后'],
  ['lateral', '外侧'],
  ['medial', '内侧'],
  ['superior', '上方'],
  ['inferior', '下方'],
  ['volar', '掌侧'],
  ['dorsal', '背侧'],
  ['palmar', '掌侧'],
  ['plantar', '足底'],
  ['intramuscular', '肌内'],
  ['subcutaneous', '皮下'],
  ['intramedullary', '髓内'],
  ['periosteal', '骨膜'],
  ['cortical', '皮质'],
  ['trabecular', '骨小梁'],
  ['comminuted', '粉碎'],
  ['displaced', '移位'],
  ['nondisplaced', '无移位'],
  ['instability', '不稳'],
  ['malalignment', '力线异常'],
  ['deformity', '畸形'],
  ['swelling', '肿胀'],
  ['tenderness', '压痛'],
  ['weakness', '无力'],
  ['numbness', '麻木'],
  ['paresthesia', '感觉异常'],
  ['radiculopathy', '神经根病'],
  ['myelopathy', '脊髓病'],
  ['claudication', '间歇性跛行'],
  ['subluxation', '半脱位'],
  ['dislocation', '脱位'],
  ['avulsion', '撕脱'],
  ['contusion', '挫伤'],
  ['sprain', '扭伤'],
  ['rupture', '断裂'],
  ['tendon', '肌腱'],
  ['ligament', '韧带'],
  ['fracture', '骨折'],
  ['effusion', '积液'],
  ['synovitis', '滑膜炎'],
  ['tenosynovitis', '腱鞘炎'],
  ['bursitis', '滑囊炎'],
  ['enthesitis', '附着点炎'],
  ['osteophyte', '骨赘'],
  ['recurrence', '复发'],
  ['metastasis', '转移'],
  ['biopsy', '活检'],
  ['benign', '良性'],
  ['malignant', '恶性'],
  ['surgical', '手术'],
  ['conservative', '保守'],
  ['eccentric', '离心性'],
  ['concentric', '向心性'],
  ['rehabilitation', '康复'],
  ['follow-up', '随访'],
  ['degenerative', '退行性'],
  ['inflammatory', '炎性'],
  ['infectious', '感染性'],
  ['ischemic', '缺血性'],
  ['hemosiderin', '含铁血黄素'],
  ['blooming', '磁敏感伪影'],
  ['synovium', '滑膜'],
  ['synovial', '滑膜'],
  ['meniscus', '半月板'],
  ['labrum', '盂唇'],
  ['subchondral', '软骨下'],
  ['cartilage', '软骨'],
  ['edema', '水肿'],
  ['hematoma', '血肿'],
  ['hemorrhage', '出血'],
  ['necrosis', '坏死'],
  ['sclerosis', '硬化'],
  ['lytic', '溶骨性'],
  ['blastic', '成骨性'],
  ['runners', '跑步者'],
  ['athletes', '运动员'],
  ['sprint', '冲刺'],
  ['trauma', '创伤'],
  ['acute', '急性'],
  ['chronic', '慢性'],
  ['partial', '部分'],
  ['complete', '完全'],
  ['stable', '稳定'],
  ['unstable', '不稳定'],
  ['common', '常见'],
  ['rare', '少见'],
  ['typical', '典型'],
  ['classic', '经典'],
  ['deep', '深部'],
  ['superficial', '浅表'],
  ['primary', '原发'],
  ['secondary', '继发'],
  ['local', '局部'],
  ['diffuse', '弥漫'],
  ['focal', '局灶'],
  ['multiple', '多发'],
  ['Achilles', '跟腱'],
  ['patellar', '髌骨'],
  ['extensor', '伸肌'],
  ['flexor', '屈肌'],
  ['rotation', '旋转'],
  ['extension', '伸展'],
  ['flexion', '屈曲'],
  ['abduction', '外展'],
  ['adduction', '内收'],
  ['supination', '旋后'],
  ['pronation', '旋前'],
  ['open', '开放'],
  ['closed', '闭合'],
  ['laceration', '撕裂伤'],
  ['attrition', '磨损'],
  ['cruciate', '交叉'],
  ['cervical', '颈椎'],
  ['thoracic', '胸椎'],
  ['lumbar', '腰椎'],
  ['sacral', '骶骨'],
  ['femur', '股骨'],
  ['tibia', '胫骨'],
  ['fibula', '腓骨'],
  ['humerus', '肱骨'],
  ['radius', '桡骨'],
  ['ulna', '尺骨'],
  ['scapula', '肩胛骨'],
  ['clavicle', '锁骨'],
  ['patella', '髌骨'],
  ['talus', '距骨'],
  ['calcaneus', '跟骨'],
  ['scaphoid', '舟骨'],
  ['olecranon', '鹰嘴'],
  ['coronoid', '冠突'],
  ['acetabulum', '髋臼'],
  ['glenoid', '关节盂'],
  ['shoulder', '肩'],
  ['elbow', '肘'],
  ['wrist', '腕'],
  ['hand', '手'],
  ['hip', '髋'],
  ['knee', '膝'],
  ['ankle', '踝'],
  ['foot', '足'],
  ['spine', '脊柱'],
  ['pelvis', '骨盆'],
  ['mass', '肿块'],
  ['nodule', '结节'],
  ['cyst', '囊肿'],
  ['tumor', '肿瘤'],
  ['lesion', '病变'],
  ['injury', '损伤'],
  ['syndrome', '综合征'],
  ['overview', '概述'],
  ['clinical', '临床'],
  ['imaging', '影像'],
  ['management', '处理'],
  ['diagnosis', '诊断'],
  ['treatment', '治疗'],
  ['observation', '观察'],
  ['injection', '注射'],
  ['excision', '切除'],
  ['debridement', '清理'],
  ['synovectomy', '滑膜切除'],
  ['arthroscopic', '关节镜'],
  ['fusion', '融合'],
  ['replacement', '置换'],
  ['osteotomy', '截骨'],
  ['decompression', '减压'],
  ['laminectomy', '椎板切除'],
  ['laminoplasty', '椎管扩大成形术'],
  ['discectomy', '椎间盘切除'],
  ['foraminotomy', '椎间孔扩大'],
  ['epiphysis', '骨骺'],
  ['metaphysis', '干骺端'],
  ['diaphysis', '骨干'],
  ['physis', '生长板'],
  ['condyle', '髁'],
  ['plateau', '平台'],
  ['tuberosity', '结节'],
  ['tear', '撕裂'],
  ['strain', '拉伤'],
  ['pain', '疼痛'],
  ['early', '早期'],
  ['late', '晚期'],
  ['mild', '轻度'],
  ['moderate', '中度'],
  ['severe', '重度'],
  ['sign', '征象'],
  ['symptom', '症状'],
  ['mechanism', '机制'],
  ['history', '病史'],
  ['pattern', '模式'],
  ['type', '型'],
  ['grade', '分级'],
  ['stage', '分期'],
  ['zone', '区'],
  ['form', '型'],
  ['variant', '变异型'],
  ['direct', '直接'],
  ['indirect', '间接'],
  ['fall', '跌倒'],
  ['running', '跑步'],
  ['jumping', '跳跃'],
  ['lifting', '举重'],
  ['training', '训练'],
  ['rehab', '康复'],
  ['collateral ligament', '副韧带'],
  ['Mallet finger', '槌状指'],
  ['Mallet', '槌状指'],
  ['PIP joint', '近侧指间关节'],
  ['DIP joint', '远侧指间关节'],
  ['PIP', '近侧指间关节'],
  ['DIP', '远侧指间关节'],
  ['MCP', '掌指关节'],
  ['compartment syndrome', '骨筋膜室综合征'],
  ['compartment', '筋膜室'],
  ['fasciotomy', '筋膜切开'],
  ['exertional', '劳力性'],
  ['postoperative', '术后'],
  ['post trauma', '创伤后'],
  ['terminal slip', '终末束'],
  ['terminal tendon', '终末腱'],
  ['zone III', 'III 区'],
  ['zone I', 'I 区'],
  ['zone V', 'V 区'],
  ['zone VIII', 'VIII 区'],
  ['soleus', '比目鱼肌'],
  ['plantaris', '跖肌'],
  ['tennis leg', '网球腿'],
  ['DVT', '深静脉血栓'],
  ['denervation', '失神经支配'],
  ['myotome', '肌节'],
  ['xanthoma', '黄瘤'],
  ['hypercholesterolemia', '高胆固醇血症'],
  ['Madelung deformity', 'Madelung 畸形'],
  ['Madelung', 'Madelung 畸形'],
  ['positive variance', '正尺骨变异'],
  ['ulnar variance', '尺骨变异'],
  ['radial inclination', '桡骨倾斜'],
  ['lunate', '月骨'],
  ['capitellum', '肱骨小头'],
  ['osteochondral', '骨软骨'],
  ['rhabdomyolysis', '横纹肌溶解'],
  ['pyomyositis', '化脓性肌炎'],
  ['myositis', '肌炎'],
  ['abscess', '脓肿'],
  ['weightlifting', '举重'],
  ['splinting', '支具固定'],
  ['continuous', '持续'],
  ['cornerstone', '核心'],
  ['bony', '骨性'],
  ['fragment', '骨片'],
  ['involvement', '累及'],
  ['compliance', '依从性'],
  ['surgery', '手术'],
  ['reconstruction', '重建'],
  ['repair', '修复'],
  ['tendinopathy', '肌腱病'],
  ['activity', '活动'],
  ['collapse', '塌陷'],
  ['retraction', '回缩'],
  ['syndesmosis', '下胫腓联合'],
  ['odontoid', '齿状突'],
  ['boutonniere', '钮孔畸形'],
  ['syringomyelia', '脊髓空洞症'],
  ['dedifferentiation', '去分化'],
  ['infiltration', '浸润'],
  ['thickening', '增厚'],
  ['narrowing', '变窄'],
  ['pathology', '病变'],
  ['mechanical', '机械性'],
  ['compression', '压迫'],
  ['fragmentation', '碎裂'],
  ['strengthening', '强化训练'],
  ['discontinuity', '连续性中断'],
  ['resorptive', '吸收性'],
  ['incidental', '偶发'],
  ['repetitive', '重复性'],
  ['overhead', '过头位'],
  ['modification', '调整'],
  ['exclude', '排除'],
  ['autoimmune', '自身免疫'],
  ['arthropathy', '关节病'],
  ['dysplasia', '发育不良'],
  ['aggressive', '侵袭性'],
  ['labral', '盂唇'],
  ['pulley', '滑车'],
  ['groin', '腹股沟'],
  ['gastroc', '腓肠肌'],
  ['axillary', '腋'],
  ['steroid', '激素'],
  ['pincer', '钳夹型'],
  ['associated', '伴发'],
  ['athlete', '运动员'],
  ['anchor', '锚钉'],
  ['stress', '应力'],
  ['sagittal', '矢状'],
  ['oblique', '斜位'],
  ['radial', '径向'],
  ['parosteal', '骨旁'],
  ['fascial', '筋膜'],
  ['cleft', '裂隙'],
  ['phleboliths', '静脉石'],
  ['groove', '沟'],
  ['notch', '切迹'],
  ['location', '部位'],
  ['phase', '期'],
  ['rotatory', '旋转性'],
  ['rapid', '快速'],
  ['juvenile', '青少年'],
  ['track', '轨迹'],
  ['sudden', '突发'],
  ['loss', '丢失'],
  ['level', '层面'],
  ['fiber', '纤维'],
  ['head', '头'],
  ['pole', '极'],
  ['body', '体部'],
  ['band', '带'],
  ['line', '线'],
  ['space', '间隙'],
  ['fluid', '液体'],
  ['test', '试验'],
  ['risk', '风险'],
  ['high', '高'],
  ['size', '大小'],
  ['bone', '骨'],
  ['joint', '关节'],
  ['disc', '间盘'],
  ['muscle', '肌肉'],
  ['nerve', '神经'],
  ['facet', '小关节'],
  ['cuff', '袖'],
  ['miss', '漏诊'],
  ['normal', '正常'],
  ['marrow', '骨髓'],
  ['fatty', '脂肪'],
  ['active', '活动性'],
  ['passive', '被动'],
  ['resting', '静息'],
  ['untreated', '未治疗'],
  ['forced', '强力'],
  ['extended', '伸展'],
  ['large', '较大'],
  ['small', '较小'],
  ['male', '男性'],
  ['female', '女性'],
  ['ring finger', '环指'],
  ['middle phalanx', '中节指骨'],
  ['proximal phalanx', '近节指骨'],
  ['nail bed', '甲床'],
  ['germinal matrix', '生发基质'],
  ['indication', '指征'],
  ['delayed', '延迟'],
  ['lag', '滞后'],
  ['dorsum', '背侧'],
  ['proportion', '比例'],
  ['pallor', '苍白'],
  ['paralysis', '麻痹'],
  ['pulselessness', '无脉'],
  ['exercise-induced', '运动诱发'],
  ['relieved', '缓解'],
  ['recurrent', '反复'],
  ['predictable', '可预测'],
  ['drop', '下垂'],
  ['tight', '张力增高'],
  ['firm', '坚硬'],
  ['palpation', '触诊'],
  ['time-critical', '时间紧迫'],
  ['diagnostic', '诊断性'],
  ['emergent', '紧急'],
  ['elective', '择期'],
  ['dressings', '敷料'],
  ['casts', '石膏'],
  ['sequelae', '后遗症'],
  ['cellulitis', '蜂窝织炎'],
  ['necrotizing fasciitis', '坏死性筋膜炎'],
  ['neurogenic', '神经源性'],
  ['radicular', '根性'],
  ['reliable', '可靠'],
  ['first-line', '一线'],
  ['physical therapy', '物理治疗'],
  ['taping', '贴扎'],
  ['bracing', '支具'],
  ['chondral', '软骨'],
  ['defect', '缺损'],
  ['microfracture', '微骨折'],
  ['maltracking', '轨迹异常'],
  ['crepitus', '摩擦音'],
  ['locking', '交锁'],
  ['apprehension', '恐试验'],
  ['minimal', '少量'],
  ['alignment', '对位'],
  ['thinning', '变薄'],
  ['full-thickness', '全层'],
  ['tilt', '倾斜'],
  ['quantification', '定量'],
  ['meniscal', '半月板'],
  ['fold', '皱襞'],
  ['plica', '皱襞'],
  ['clicking', '弹响'],
  ['limited', '受限'],
  ['arthrography', '关节造影'],
  ['arthroscopy', '关节镜'],
  ['impingement', '撞击'],
  ['catching', '卡顿'],
  ['giving way', '打软腿'],
  ['positive', '阳性'],
  ['negative', '阴性'],
  ['night', '夜间'],
  ['sitting', '坐位'],
  ['discomfort', '不适'],
  ['morphology', '形态'],
  ['longitudinal', '纵向'],
  ['flap', '瓣状'],
  ['etiology', '病因'],
  ['crossover', '交叉征'],
  ['explain', '解释'],
  ['denervation', '失神经支配'],
  ['myotome', '肌节'],
  ['seeded', '种植'],
  ['contiguous', '邻近'],
  ['spread', '蔓延'],
  ['symmetric', '对称'],
  ['proximal', '近端'],
  ['weakness', '无力'],
  ['leukocytosis', '白细胞增多'],
  ['antibodies', '抗体'],
  ['rash', '皮疹'],
  ['heliotrope', '向阳疹'],
  ['papules', '丘疹'],
  ['suppurative', '化脓性'],
  ['fibrosis', '纤维化'],
  ['immunocompromised', '免疫抑制'],
  ['tropical', '热带'],
  ['region', '地区'],
  ['diabetic', '糖尿病'],
  ['viral', '病毒'],
  ['hematogenous', '血源性'],
  ['inflammation', '炎症'],
  ['elevated', '升高'],
  ['fever', '发热'],
  ['swan neck', '天鹅颈'],
  ['possible', '可能'],
  ['combined', '合并'],
  ['chronic', '慢性'],
  ['grip', '握力'],
  ['block', '阻挡'],
  ['sequela', '后遗症'],
  ['surrounding', '周围'],
  ['coronal', '冠状位'],
  ['stress test', '应力试验'],
  ['immobilize', '固定'],
  ['pressure', '压力'],
  ['skin', '皮肤'],
  ['excessive', '过度'],
  ['success', '成功'],
  ['allow', '允许'],
  ['movement', '活动'],
  ['evaluate', '评估'],
  ['unstable', '不稳定'],
  ['stable', '稳定'],
  ['superficial', '浅表'],
  ['deep', '深部'],
  ['anterior', '前'],
  ['posterior', '后'],
  ['lateral', '外侧'],
  ['medial', '内侧'],
  ['dorsal', '背侧'],
  ['volar', '掌侧'],
  ['palmar', '掌侧'],
  ['plantar', '足底'],
  ['distal', '远端'],
  ['proximal', '近端'],
  ['monitor', '监测'],
  ['screening', '筛查'],
  ['ball sports', '球类运动'],
  ['work-related', '工伤相关'],
  ['articular surface', '关节面'],
  ['surface', '面'],
  ['incongruity', '不匹配'],
  ['symptomatic', '有症状'],
  ['isolated', '孤立'],
  ['tibial', '胫骨'],
  ['ulnar', '尺骨'],
  ['biceps', '肱二头肌'],
  ['crush', '挤压'],
  ['terminal', '终末'],
  ['weeks', '周'],
  ['fixation', '固定'],
  ['function', '功能'],
  ['cosmetic', '美容'],
  ['demand', '需求'],
  ['cause', '原因'],
  ['unrelated', '非相关'],
  ['arthritis', '关节炎'],
  ['splint', '夹板'],
  ['stability', '稳定性'],
  ['base', '基底'],
  ['stub', '戳伤'],
  ['most', '多数'],
  ['signal', '信号'],
  ['flow void', '流空'],
  ['post-exercise', '运动后'],
  ['post-jamming', '扭伤后'],
  ['post-viral', '病毒感染后'],
  ['post-trauma', '创伤后'],
  ['post-traumatic', '创伤后'],
  ['postoperative', '术后'],
  ['preoperative', '术前'],
  ['overuse', '过度使用'],
  ['overload', '过载'],
  ['maltracking', '轨迹异常'],
  ['softening', '软化'],
  ['fissuring', '裂隙'],
  ['crepitus', '摩擦音'],
  ['stairs', '上下楼梯'],
  ['squat', '深蹲'],
  ['prolonged', '长时间'],
  ['movie sign', '电影征'],
  ['movie', '电影'],
  ['locking', '交锁'],
  ['unless', '除非'],
  ['free body', '游离体'],
  ['height', '高度'],
  ['grind', '研磨试验'],
  ['effusion', '积液'],
  ['defect', '缺损'],
  ['selected', '精选病例'],
  ['trochleoplasty', '滑车成形术'],
  ['reconstruction', '重建'],
  ['instability', '不稳'],
  ['delayed', '延迟'],
  ['diagnosis', '诊断'],
  ['average', '平均'],
  ['years', '年'],
  ['limited ROM', '活动范围受限'],
  ['ROM', '活动范围'],
  ['night pain', '夜间痛'],
  ['impingement test', '撞击试验'],
  ['FADIR', 'FADIR'],
  ['undermining', '潜行性'],
  ['paralabral', '盂唇旁'],
  ['morphology', '形态'],
  ['cam', 'Cam'],
  ['pincer', '钳夹型'],
  ['crossover sign', '交叉征'],
  ['posterior wall sign', '后壁征'],
  ['wall sign', '壁征'],
  ['contrast', '对比剂'],
  ['cleft', '裂隙'],
  ['edema', '水肿'],
  ['hypoechoic', '低回声'],
  ['hyperechoic', '高回声'],
  ['hyperintense', '高信号'],
  ['hypointense', '低信号'],
  ['hypoechoic', '低回声'],
  ['bedside', '床旁'],
  ['dynamic', '动态'],
  ['return-to-sport', '重返运动'],
  ['return to sport', '重返运动'],
  ['progressive', '渐进性'],
  ['isometric', '等长'],
  ['eccentric', '离心性'],
  ['concentric', '向心性'],
  ['bruising', '瘀斑'],
  ['audible', '可闻及'],
  ['pop', '弹响'],
  ['stretch', '拉伸'],
  ['scar', '瘢痕'],
  ['formation', '形成'],
  ['involvement', '累及'],
  ['tendon involvement', '肌腱受累'],
  ['free tendon', '游离腱'],
  ['prolonged', '延长'],
  ['recovery', '恢复'],
  ['RTP', '重返运动'],
  ['prevention', '预防'],
  ['evidence', '循证'],
  ['feathering', '羽毛状'],
  ['tracking', '延伸'],
  ['fluid tracking', '液体延伸'],
  ['complex', '复杂'],
  ['foreign body', '异物'],
  ['mobilization', '活动'],
  ['aggressive', '积极'],
  ['re-bleed', '再出血'],
  ['kicking', '踢球'],
  ['sports hernia', '运动性疝'],
  ['osteitis pubis', '耻骨炎'],
  ['symphysis', '联合'],
  ['concomitant', '合并'],
  ['treatment', '治疗'],
  ['strategy', '策略'],
  ['origin', '起点'],
  ['abduction', '外展'],
  ['sprint', '冲刺'],
  ['sprinting', '冲刺'],
  ['Nordic', 'Nordic'],
  ['ischial', '坐骨'],
  ['tuberosity', '结节'],
  ['avulsion', '撕脱'],
  ['radiculopathy', '神经根病'],
  ['bedside', '床旁'],
  ['screen', '筛查'],
  ['finger', '指'],
  ['pin/screw', '克氏针/螺钉'],
  ['emergency', '急诊'],
  ['revascularization', '再血管化'],
  ['cyclists', '骑行者'],
  ['military', '军人'],
  ['capillary perfusion', '毛细血管灌注'],
  ['perfusion', '灌注'],
  ['ischemia', '缺血'],
  ['progression', '进展'],
  ['irreversible', '不可逆'],
  ['reversible', '可逆'],
  ['unreliable', '不可靠'],
  ['pain out of proportion', '疼痛与伤情不成比例'],
  ['out of proportion', '与伤情不成比例'],
  ['peroneal nerve', '腓深神经'],
  ['peroneal', '腓骨'],
  ['Pedowitz criteria', 'Pedowitz 标准'],
  ['differential', '压差'],
  ['myonecrosis', '肌坏死'],
  ['boundary', '边界'],
  ['anatomy', '解剖'],
  ['cross-section', '横断面'],
  ['affected', '受累'],
  ['compartments', '筋膜室'],
  ['confirmation', '确认'],
  ['non-enhancing', '无强化'],
  ['necrotic', '坏死'],
  ['non-acute', '非急性'],
  ['if needed', '如需要'],
  ['after', '之后'],
  ['avoid', '避免'],
  ['never delay', '切勿延误'],
  ['clinical emergency', '临床急诊'],
  ['setting', '场景'],
  ['proportion', '比例'],
  ['rest', '休息'],
  ['leg', '小腿'],
  ['delay', '延迟'],
  ['exercise', '运动'],
  ['pre/post exercise', '运动前后'],
  ['image', '影像'],
  ['enhancing', '强化'],
  ['necrotizing', '坏死性'],
  ['fasciitis', '筋膜炎'],
  ['fascial compartment', '筋膜室'],
  ['post-fracture', '骨折后'],
  ['no imaging', '无需影像'],
  ['ligamentum flavum', '黄韧带']
];

const PHRASES = [...PHRASES_RAW, ...GENERAL_PHRASES, ...EXTRA_PHRASES, ...BULK_PHRASES, ...GENERAL_WORDS, ...EXTRA_WORDS, ...BULK_WORDS].sort(
  (a, b) => b[0].length - a[0].length
);

const ROMAN = /^(I{1,3}|IV|VI{0,3}|VIII|IX|XI{0,2}|XII)$/i;

const SKIP_GLOSS = new Set(['II', 'III', 'IV', 'VI', 'VII', 'VIII', 'IX', 'X', 'XI', 'XII', 'CT', 'MRI', 'MR', 'MRA', 'ACL', 'AC']);

function abbrevRegex(abbr) {
  const escaped = abbr.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  // 完整词界 + 已标注不再重复（避免 MR→MRI、LC→LCEA）
  return new RegExp(`(?<![A-Za-z0-9])${escaped}(?!（)(?![A-Za-z0-9])`, 'g');
}

/** 清除重复叠加的缩写标注 */
function dedupeAbbrevGloss(text) {
  if (!text || !/（/.test(text)) return text;
  let s = collapseNestedGloss(String(text));
  let prev;
  do {
    prev = s;
    s = s.replace(/（([^（）]{1,48})）（\1）/g, '（$1）');
  } while (s !== prev);
  return s
    .replace(/(（[^（）]{1,48}）)\1+/g, '$1')
    .replace(/([A-Z][A-Z0-9-]{1,})(（[^（）]{1,48}）)\1\2/g, '$1$2');
}

/** 为英文缩写追加中文全称：MRI → MRI（磁共振成像） */
export function glossAbbreviations(text) {
  if (text == null) return '';
  let s = String(text);
  if (!/[A-Z]{2,}/.test(s)) return s;

  for (const [abbr, zh] of ABBREV_GLOSS_UNIQUE) {
    if (!abbr || !zh || abbr === zh || SKIP_GLOSS.has(abbr)) continue;
    s = s.replace(abbrevRegex(abbr), `${abbr}（${zh}）`);
  }
  return dedupeAbbrevGloss(s);
}

function isKeptWord(w) {
  const u = w.toUpperCase();
  return KEEP_UPPER.has(u) || BULK_KEEP_LOWER.has(w.toLowerCase()) || ROMAN.test(w) || /^T[12]$/.test(u);
}

function allEnglishKept(s) {
  if (!/[a-zA-Z]/.test(s)) return true;
  // 中英混合一律走润色，避免 NORDIC/MRI 等白名单导致整句跳过
  if (/[\u4e00-\u9fff]/.test(s)) return false;
  const words = s.match(/[A-Za-z]{2,}/g) || [];
  if (!words.length) return true;
  return words.every(isKeptWord);
}

/** 修复历史误替换造成的乱码 */
const GARBLED_FIXES = [
  ['unre晚期d', '未修复'],
  ['re晚期d', '修复'],
  ['work-re晚期d', '工伤'],
  ['征象al', '信号'],
  ['per融合', '灌注'],
  ['Col外侧', '副韧带'],
  ['poly肌炎', '多肌炎'],
  ['dermato肌炎', '皮肌炎'],
  ['征象al abnormality', '信号异常'],
  ['征象al', '信号'],
  ['畸形 畸形', '畸形'],
  ['天鹅颈畸形 畸形', '天鹅颈畸形'],
  ['LC（软骨）EA（外侧中心边缘角）', 'LCEA（外侧中心边缘角）'],
  ['LC（软骨）EA', 'LCEA'],
  ['MRI（磁共振成像）', 'MRI'],
  ['CT（计算机断层扫描）', 'CT'],
  ['MR（磁共振）I（磁共振成像）', 'MRI'],
  ['MR（磁共振）（磁共振血管成像）', 'MRA'],
  ['MR（磁共振）SA（耐甲氧西林金黄色葡萄球菌）', 'MRSA'],
  ['MR（磁共振）C（医学研究委员会分级）', 'MRC'],
  ['MR（磁共振） 关节造影', 'MRI 关节造影'],
  ['MR（磁共振）', 'MRI'],
  ['AC（肩锁关节）L（前交叉韧带）', 'ACL'],
  ['AC（肩锁关节）L', 'ACL']
];

/** 通顺性修正（去空格后仍存在的固定搭配） */
const TIDY_PHRASES = [
  ['骨化 黄韧带', '黄韧带骨化'],
  ['no 影像', '无需影像'],
  ['post-骨折', '骨折后'],
  ['post-创伤', '创伤后'],
  ['fascial 筋膜室', '筋膜室'],
  ['筋膜 筋膜室', '筋膜室'],
  ['弹响 声', '弹响声'],
  ['保肢 截肢', '保肢/截肢'],
  ['微创 开放', '微创/开放'],
  ['液体 信号', '液体信号'],
  ['天鹅颈 畸形', '天鹅颈畸形'],
  ['临床 为主', '临床为主'],
  ['本库 型=', '本库 type='],
  ['、 ', '、'],
  [' ，', '，'],
  [' ；', '；'],
  [' ：', '：'],
  ['缓解 休息', '休息后缓解'],
  ['缓解休息', '休息后缓解'],
  ['临床 + ', '临床与'],
  ['→ ', '→'],
  ['、 ', '、']
];

function phraseRegex(en) {
  const escaped = en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  if (/[\s'\u2019/-]/.test(en)) return new RegExp(escaped, 'gi');
  return new RegExp(`(?<![A-Za-z])${escaped}(?![A-Za-z])`, 'gi');
}

/** 删除中文间多余空格，修正标点与重复词 */
export function tidyChinese(text) {
  if (text == null) return '';
  let s = String(text).trim();
  if (!s) return s;

  for (const [bad, good] of GARBLED_FIXES) {
    s = s.split(bad).join(good);
  }
  for (const [bad, good] of TIDY_PHRASES) {
    s = s.split(bad).join(good);
  }

  s = s.replace(/([\u4e00-\u9fff]{1,8}) \1/g, '$1');

  let prev;
  do {
    prev = s;
    s = s.replace(/([\u4e00-\u9fff\u3400-\u4dbf]) ([\u4e00-\u9fff\u3400-\u4dbf])/g, '$1$2');
  } while (s !== prev);

  s = s
    .replace(/([\u4e00-\u9fff\u3400-\u4dbf]) ([，。；：、])/g, '$1$2')
    .replace(/([（]) ([\u4e00-\u9fff\u3400-\u4dbf])/g, '$1$2')
    .replace(/([\u4e00-\u9fff\u3400-\u4dbf]) ([）])/g, '$1$2')
    .replace(/ +([，。；：、])/g, '$1')
    .replace(/([，。；：、]) +/g, '$1')
    .replace(/[ \t]{2,}/g, ' ')
    .replace(/([\u4e00-\u9fff]) \/ ([\u4e00-\u9fff])/g, '$1/$2')
    .trim();

  return s;
}

export function polishChinese(text) {
  if (text == null) return '';
  let s = String(text).trim();
  if (!s) return s;

  if (allEnglishKept(s)) return tidyChinese(glossAbbreviations(s));
  if (!/[a-zA-Z]/.test(s)) return tidyChinese(s);

  for (const [bad, good] of GARBLED_FIXES) {
    s = s.split(bad).join(good);
  }

  for (const [en, zh] of PHRASES) {
    s = s.replace(phraseRegex(en), zh);
  }

  s = s
    .replace(/\b(the|a|an|of|in|on|at|for|from|to|by|with|and|or|vs|versus)\b/gi, '')
    .replace(/\s{2,}/g, ' ')
    .replace(/\s+([，。；：、])/g, '$1')
    .replace(/([，。；：])\s+/g, '$1')
    .replace(/\(\s*\)/g, '')
    .trim();

  return tidyChinese(glossAbbreviations(s));
}

export function polishPair([a, b]) {
  return [polishChinese(a), polishChinese(b)];
}

export function tidyDetail(det) {
  if (!det || typeof det !== 'object') return det;
  return {
    overview: tidyChinese(det.overview),
    epi: tidyChinese(det.epi),
    pathophys: tidyChinese(det.pathophys),
    clinical: (det.clinical || []).map(tidyChinese).filter(Boolean),
    staging: tidyChinese(det.staging),
    imagingKeys: (det.imagingKeys || []).map(([a, b]) => [tidyChinese(a), tidyChinese(b)]),
    modalities: (det.modalities || []).map(([m, d]) => [tidyChinese(glossAbbreviations(m)), tidyChinese(d)]),
    mgmt: (det.mgmt || []).map(tidyChinese).filter(Boolean),
    ddx: (det.ddx || []).map(tidyChinese).filter(Boolean),
    pitfalls: (det.pitfalls || []).map(tidyChinese).filter(Boolean),
    pearls: (det.pearls || []).map(tidyChinese).filter(Boolean),
    ...(det.sources ? { sources: det.sources } : {})
  };
}

export function polishDetail(det) {
  const out = tidyDetail({
    overview: polishChinese(det?.overview),
    epi: polishChinese(det?.epi),
    pathophys: polishChinese(det?.pathophys),
    clinical: (det?.clinical || []).map(polishChinese).filter(Boolean),
    staging: polishChinese(det?.staging),
    imagingKeys: (det?.imagingKeys || []).map(polishPair),
    modalities: (det?.modalities || []).map(([m, d]) => [polishChinese(m), polishChinese(d)]),
    mgmt: (det?.mgmt || []).map(polishChinese).filter(Boolean),
    ddx: (det?.ddx || []).map(polishChinese).filter(Boolean),
    pitfalls: (det?.pitfalls || []).map(polishChinese).filter(Boolean),
    pearls: (det?.pearls || []).map(polishChinese).filter(Boolean)
  });
  if (det?.sources) out.sources = det.sources;
  return out;
}

/** 统计仍含非保留英文词的数量（2 字母及以上，用于验证） */
export function countEnglishWords(text) {
  const words = String(text || '').match(/[A-Za-z]{2,}/g) || [];
  return words.filter(w => !isKeptWord(w)).length;
}

/** 从详情对象文本值统计非保留英文（不含 JSON 字段名） */
export function countDetailEnglishWords(det) {
  if (!det || typeof det !== 'object') return 0;
  let n = 0;
  const walk = (v) => {
    if (v == null) return;
    if (typeof v === 'string') {
      n += countEnglishWords(v);
      return;
    }
    if (Array.isArray(v)) {
      v.forEach(walk);
      return;
    }
    if (typeof v === 'object') walk(Object.values(v));
  };
  walk(det);
  return n;
}
