/** Auto-generated — 2+ 字母英文 → 中文批量映射 */
export const BULK_KEEP_LOWER = new Set(["aber","acdf","aci","acnes","afp","ahlb","akp","alif","allg","allman","alonzo","anderson-d","ao","ap","arcuate","arnold","arnold-hilgartner","asia","aspscr","aspscr1","aspscr1-tfe3","auts","avm","b3","badge","bado","beard","berndt-harty","bicipital","bigliani","bloc","blount","bmi","bohler","bonar","boxer","brien","bristow","broberg","broberg-morrey","brown-s","brucella","buford","buschke-ollendorff","ca","cad","caffey","cccs","ccp","cd","cd31","cdk","cdk4","ce","chl","chopart","chter","cierny-mader","cleary","cleary-omar","cn","cofield","col","col1a1-pdgfb","costochondritis","cpp","crps","cs","csf1","ctnnb","ctnnb1","danis-weber","das","dashboard","ddit","dditt3","denis","dens","der","dhs","down","driscoll","dunn","durie-salmon","eaton","ecu","edi","edi-allg","eicess","eichenholtz","eip","ema","en","endobutton","erg","essex-lopresti","ets","euro","euro-ewing","ewsr","ewsr1","ewsr1-ddit3","ewsr1-fli1","ext","ext1","ext2","fast","fh","ficat-arlet","fielding","fli","fnclcc","forestier","fosb","four-corner","fredericson","frykberg","frykman","fus","fus-ddit3","fx","gamekeeper","geissler","genant","gerdy","gilula","gissane","goats","gottron","grauer","grisel","gull-wing","gustilo","gy","ha","habermeyer","harris","he","heijde","hilgartner","hill-sachs","hippel","hippel-lindau","hla-b27","hoffmann","hop","hotchkiss","hpf","hs","hto","i-iv","ids","if","ifn","igf-2","iia","iib","il-17","imatinib","infraspinous","ing","ip","issva","iwano","jaffe-campanacci","jaffe-lichtenstein","johansson","johnell","kager","kasabach-merritt","keinbock","kellgren-lawrence","keystone","kienb","koshino","laborer","lafosse","langenski","lanzetta","larsen","latarjet","lauge-hansen","lc","ld","ldh","ldl-c","lee","legg-calv","leri-weill","levine-edwards","lf","lgc","lgc-os","lhermitte","lichtman","lindau","ll","m3","m4","mayo","mccune-albright","mcmaster","mdm","mdm2","mghl","mhe","mitsubishi","miyazaki","mmhg","mod","mohs","moll","morrey","mr","mrsa","mtp","mumford","myh","myh9-usp6","nab","nab2-stat6","newman","nf","nf1","no","noonan","not","oestern","of","oh","ok","ok-432","omar","op","os","osgood","osgood-schlatter","p53","pa","patrick","patte","pauwels","pavlik","pd-fs","pdgfr","pec","pet-ct","pf","pfirmann","pilon","plafond","plag","plag1","plif","pm","prieto","propionibacterium","proteus","q12","q6h","qct","r-chop","r-iss","r0","radialhead","ranawat","rcl","rct","re","redlund","redlund-johnell","regimental","remplissage","resnick","rf","robert","robinson","rtner","rule","s-100","salter","salter-harris","samilson","samilson-prieto","sanders-frykberg","sandwich","schlatter","scottie","sea","seddon","severin","sghl","shox","sinding","sinding-larsen-johansson","sit","sl","sle","slj","snyder","sorensen","spica","spinoglenoid","ss","ss18-ssx","stieda","stryker","sub","supraspinous","sustentaculum","t-cell","t12","t12-l1","t8","t9","t90","takakura","tfe3","tha","thompson","tibialis","tile","tillaux","tki","tlif","tnm","toh","tonnis","trendelenburg","tscherne","tt-tg","turner","turners","ucl","uka","uop","up","v600e","van","verdan","vest","vhl","vitd","volat","von","vs","watanabe","watson","wbc","wer","west","wiberg","wilson","wiltse","wiltse-newman","wright","yao","yergason"]);

export const BULK_PHRASES = [
  ["heterotopic ossification", "异位骨化"],
  ["radiofrequency ablation", "射频消融"],
  ["pars interarticularis", "椎弓根峡部"],
  ["compartment syndrome", "骨筋膜室综合征"],
  ["adhesive capsulitis", "粘连性关节囊炎"],
  ["suprascapular nerve", "肩胛上神经"],
  ["spinoglenoid notch", "冈盂切迹"],
  ["avascular necrosis", "骨坏死"],
  ["plantar fasciitis", "足底筋膜炎"],
  ["bone marrow edema", "骨髓水肿"],
  ["blooming artifact", "磁敏感伪影"],
  ["latissimus dorsi", "背阔肌"],
  ["regimental badge", "军徽征"],
  ["gamekeeper thumb", "Gamekeeper拇指"],
  ["intra-substance", "实质内"],
  ["juxta-articular", "关节旁"],
  ["frozen shoulder", "冻结肩"],
  ["achilles tendon", "跟腱"],
  ["stress fracture", "应力性骨折"],
  ["disc herniation", "椎间盘突出"],
  ["well-preserved", "保存良好"],
  ["terrible triad", "严重三联征"],
  ["kissing lesion", "对吻样病变"],
  ["boxer fracture", "Boxer骨折"],
  ["radiating pain", "放射痛"],
  ["trigger finger", "扳机指"],
  ["peroneal nerve", "腓总神经"],
  ["bucket-handle", "桶柄样"],
  ["pathologic fx", "病理性骨折"],
  ["bucket handle", "桶柄样"],
  ["shooting pain", "放射痛"],
  ["carpal tunnel", "腕管"],
  ["meniscal cyst", "半月板囊肿"],
  ["ganglion cyst", "腱鞘囊肿"],
  ["mallet finger", "槌状指"],
  ["digital nerve", "指神经"],
  ["first-degree", "一级"],
  ["donut-shaped", "甜甜圈样"],
  ["celery stalk", "芹菜杆样"],
  ["ldl lowering", "降LDL"],
  ["buddy taping", "邻指固定"],
  ["shin splints", "胫骨应力综合征"],
  ["tennis elbow", "网球肘"],
  ["loose bodies", "游离体"],
  ["rotator cuff", "肩袖"],
  ["gre blooming", "GRE磁敏感伪影"],
  ["tea-colored", "茶色"],
  ["scottie dog", "Scottie犬征"],
  ["bowtie sign", "领结征"],
  ["goats beard", "山羊须征"],
  ["painful arc", "疼痛弧"],
  ["os trigonum", "距后三角骨"],
  ["four corner", "四角"],
  ["facet joint", "小关节"],
  ["spinal cord", "脊髓"],
  ["side-lying", "侧卧"],
  ["flow voids", "流空信号"],
  ["loose body", "游离体"],
  ["nerve root", "神经根"],
  ["break-off", "撕脱"],
  ["empty can", "空罐试验"],
  ["break off", "撕脱"],
  ["lift-off", "抬离"],
  ["step-off", "台阶样"],
  ["step off", "台阶样"],
  ["one-way", "单向"],
  ["x-ray", "X线"],
];

export const BULK_WORDS = [
  ["spondyloepiphyseal", "脊椎骺发育不良"],
  ["immunosuppression", "免疫抑制"],
  ["intertrochanteric", "转子间"],
  ["acetabularization", "髋臼化"],
  ["musculotendinous", "肌腱结合部"],
  ["occipitocervical", "枕颈"],
  ["hypophosphatemic", "低磷"],
  ["hemangioblastoma", "血管母细胞瘤"],
  ["myelomeningocele", "脊髓脊膜膨出"],
  ["spondylodiscitis", "椎间盘炎"],
  ["unicompartmental", "单髁"],
  ["osteopoikilosis", "骨斑点症"],
  ["dermatomyositis", "皮肌炎"],
  ["semimembranosus", "半膜肌"],
  ["retroperitoneum", "腹膜后"],
  ["intermetatarsal", "跖间"],
  ["atherosclerotic", "动脉粥样硬化"],
  ["circumferential", "环周"],
  ["melorheostosis", "蜡油样骨病"],
  ["multiloculated", "多房"],
  ["hydroxyapatite", "羟基磷灰石"],
  ["retromalleolar", "踝后"],
  ["cardiovascular", "心血管"],
  ["bisphosphonate", "双膦酸盐"],
  ["acromiohumeral", "肩肱"],
  ["autoantibodies", "自身抗体"],
  ["alkalinization", "碱化"],
  ["osteodystrophy", "骨营养不良"],
  ["anterosuperior", "前上"],
  ["radiofrequency", "射频"],
  ["individualized", "个体化"],
  ["syndesmophyte", "韧带骨赘"],
  ["osteonecrosis", "骨坏死"],
  ["hypermobility", "松弛"],
  ["stabilization", "稳定化"],
  ["interposition", "嵌入"],
  ["metatarsalgia", "跖痛"],
  ["anterolateral", "前外侧"],
  ["myoglobinuria", "肌红蛋白尿"],
  ["suprascapular", "肩胛上"],
  ["individualize", "个体化"],
  ["granulomatous", "肉芽肿性"],
  ["synchondrosis", "软骨结合"],
  ["resuscitation", "复苏"],
  ["fasciculation", "束颤"],
  ["atlantodental", "寰齿"],
  ["developmental", "发育性"],
  ["neurosurgical", "神经外科"],
  ["hyperreflexia", "反射亢进"],
  ["deterioration", "恶化"],
  ["bioabsorbable", "可吸收"],
  ["intrarticular", "关节内"],
  ["intercondylar", "髁间"],
  ["physiotherapy", "理疗"],
  ["peritendinous", "腱周围"],
  ["polymyositis", "多肌炎"],
  ["presentation", "表现"],
  ["interdigital", "趾间"],
  ["atlantoaxial", "寰枢"],
  ["osteoporosis", "骨质疏松"],
  ["meniscectomy", "半月板切除"],
  ["hypertrophic", "肥厚"],
  ["irregularity", "不规则"],
  ["trochanteric", "转子"],
  ["sternocostal", "胸肋"],
  ["dorsiflexion", "背伸"],
  ["concurrently", "同时"],
  ["xanthomatous", "黄瘤样"],
  ["intermediate", "中间型"],
  ["invagination", "内陷"],
  ["supraglenoid", "盂上"],
  ["glenohumeral", "盂肱"],
  ["vascularized", "血管化"],
  ["reattachment", "再附着"],
  ["interosseous", "骨间"],
  ["recreational", "休闲"],
  ["midsubstance", "中段"],
  ["articulation", "关节"],
  ["biomechanics", "生物力学"],
  ["interstitial", "间质"],
  ["electrolytes", "电解质"],
  ["hyperkalemia", "高钾"],
  ["neurotrophic", "神经营养"],
  ["heterozygous", "杂合"],
  ["accumulation", "沉积"],
  ["myelomalacia", "脊髓软化"],
  ["suboccipital", "枕下"],
  ["irritability", "易激惹"],
  ["consultation", "会诊"],
  ["tibiofemoral", "胫股"],
  ["prostacyclin", "前列环素"],
  ["diarthrodial", "滑膜"],
  ["tibiofibular", "胫腓"],
  ["antecubital", "肘前"],
  ["embryologic", "胚胎性"],
  ["disturbance", "干扰"],
  ["significant", "显著"],
  ["sensitivity", "敏感度"],
  ["transaction", "事务"],
  ["antibiotics", "抗生素"],
  ["procurvatum", "后凸"],
  ["nonspecific", "非特异"],
  ["problematic", "问题性"],
  ["macrocystic", "大囊性"],
  ["microcystic", "小囊性"],
  ["misdiagnose", "误诊"],
  ["destruction", "破坏"],
  ["association", "关联"],
  ["intolerance", "不耐受"],
  ["advancement", "前移"],
  ["preventable", "可预防"],
  ["combination", "联合"],
  ["neuropraxia", "神经失用"],
  ["axonotmesis", "轴突断伤"],
  ["neurotmesis", "神经断伤"],
  ["xanthelasma", "睑黄瘤"],
  ["discography", "间盘造影"],
  ["craniectomy", "颅骨切除"],
  ["comorbidity", "合并症"],
  ["mesenchymal", "间充质"],
  ["metaphyseal", "干骺端"],
  ["microinjury", "微损伤"],
  ["collateral", "副"],
  ["prevalence", "患病率"],
  ["hypoplasia", "发育不全"],
  ["relocation", "复位"],
  ["arthrogram", "关节造影"],
  ["trochanter", "大转子"],
  ["capsulitis", "关节囊炎"],
  ["dehiscence", "裂开"],
  ["neuropathy", "神经病"],
  ["disruption", "中断"],
  ["clinically", "临床"],
  ["brachialis", "肱肌"],
  ["clavicular", "锁骨"],
  ["pectoralis", "胸大肌"],
  ["adaptation", "适应"],
  ["perineural", "神经周围"],
  ["entrapment", "卡压"],
  ["collection", "聚集"],
  ["malignancy", "恶性"],
  ["peripheral", "周围"],
  ["elongation", "延长"],
  ["multilevel", "多节段"],
  ["flattening", "变扁"],
  ["radioulnar", "桡尺"],
  ["vulnerable", "易损"],
  ["carpectomy", "腕骨切除"],
  ["idiopathic", "特发性"],
  ["detachment", "撕脱"],
  ["correction", "矫正"],
  ["pathologic", "病理性"],
  ["threatened", "威胁性"],
  ["compromise", "受损"],
  ["lipomatous", "脂肪性"],
  ["iatrogenic", "医源性"],
  ["multifocal", "多灶"],
  ["supportive", "支持"],
  ["creatinine", "肌酐"],
  ["homozygous", "纯合"],
  ["macrophage", "巨噬细胞"],
  ["tendinitis", "腱炎"],
  ["percentage", "百分比"],
  ["infarction", "梗死"],
  ["platybasia", "扁颅底"],
  ["sclerotome", "生骨节"],
  ["gadolinium", "钆"],
  ["spasticity", "痉挛"],
  ["corpectomy", "椎体切除"],
  ["meningioma", "脑膜瘤"],
  ["wheelchair", "轮椅"],
  ["crescentic", "新月形"],
  ["sacroiliac", "骶髂"],
  ["dermatomal", "皮节"],
  ["endoscopic", "内镜"],
  ["meniscoid", "颈椎间盘疝"],
  ["localized", "局限"],
  ["formative", "形成期"],
  ["tonsillar", "扁桃体"],
  ["segmental", "节段性"],
  ["trimester", "孕期"],
  ["abdominal", "腹"],
  ["sensation", "感觉"],
  ["retracted", "回缩"],
  ["essential", "必要"],
  ["squeezing", "挤压"],
  ["sensitive", "敏感"],
  ["detection", "检出"],
  ["otherwise", "否则"],
  ["hydration", "补液"],
  ["myoglobin", "肌红蛋白"],
  ["metabolic", "代谢"],
  ["thickness", "厚度"],
  ["thickened", "增厚"],
  ["scoliosis", "侧弯"],
  ["irregular", "不规则"],
  ["extremity", "肢体"],
  ["insidious", "隐匿"],
  ["infantile", "婴儿型"],
  ["reproduce", "再现"],
  ["popliteal", "腘窝"],
  ["sublabral", "盂下"],
  ["capitulum", "肱骨小头"],
  ["decreased", "减少"],
  ["trochlear", "滑车"],
  ["foraminal", "椎间孔"],
  ["capillary", "毛细血管"],
  ["increased", "增加"],
  ["dimension", "维度"],
  ["streaking", "条纹"],
  ["exclusion", "排除"],
  ["endurance", "耐力"],
  ["asymmetry", "不对称"],
  ["permanent", "永久"],
  ["selective", "选择性"],
  ["radiating", "放射"],
  ["massaging", "按摩"],
  ["orthotics", "矫形鞋垫"],
  ["malleolus", "踝"],
  ["endoscopy", "内镜"],
  ["potassium", "钾"],
  ["elevation", "升高"],
  ["cutaneous", "皮肤"],
  ["diffusely", "弥漫"],
  ["different", "不同"],
  ["relatives", "亲属"],
  ["ventricle", "脑室"],
  ["ossiculum", "小骨"],
  ["terminale", "终丝"],
  ["committee", "委员会"],
  ["diffusion", "扩散"],
  ["clockwise", "顺时针"],
  ["vertebral", "椎体"],
  ["candidacy", "候选"],
  ["neurogram", "神经成像"],
  ["blooming", "磁敏感伪影"],
  ["forefoot", "前足"],
  ["worsened", "加重"],
  ["mediated", "介导"],
  ["drainage", "引流"],
  ["nonunion", "不愈合"],
  ["phlegmon", "蜂窝织炎样"],
  ["marginal", "边缘"],
  ["clenched", "握拳"],
  ["climbing", "攀爬"],
  ["referred", "牵涉"],
  ["adhesive", "粘连"],
  ["accuracy", "准确度"],
  ["fibrosus", "纤维环"],
  ["anatomic", "解剖"],
  ["consider", "考虑"],
  ["standard", "标准"],
  ["myelitis", "脊髓炎"],
  ["coverage", "覆盖"],
  ["cleavage", "分裂"],
  ["ganglion", "腱鞘"],
  ["revision", "翻修"],
  ["malunion", "畸形愈合"],
  ["capitate", "头状骨"],
  ["leveling", "调平"],
  ["snuffbox", "鼻烟壶"],
  ["wrinkles", "皱纹"],
  ["envelope", "套"],
  ["atypical", "非典型"],
  ["terrible", "严重"],
  ["external", "外侧"],
  ["adjacent", "邻近"],
  ["scarring", "瘢痕"],
  ["anabolic", "合成代谢"],
  ["disorder", "障碍"],
  ["luxation", "脱位"],
  ["puncture", "穿刺"],
  ["neoplasm", "肿瘤"],
  ["maneuver", "手法"],
  ["repeated", "反复"],
  ["downhill", "下坡"],
  ["mobility", "活动度"],
  ["hindfoot", "后足"],
  ["hallmark", "特征"],
  ["toxicity", "毒性"],
  ["oliguria", "少尿"],
  ["dialysis", "透析"],
  ["brachial", "臂"],
  ["orthotic", "矫形器"],
  ["receptor", "受体"],
  ["hyperldl", "高LDL"],
  ["painless", "无痛"],
  ["tuberous", "结节性"],
  ["criteria", "标准"],
  ["shunting", "分流"],
  ["interval", "间距"],
  ["bacteria", "细菌"],
  ["diabetes", "糖尿病"],
  ["stepwise", "阶梯式"],
  ["diameter", "直径"],
  ["seizures", "癫痫"],
  ["genetics", "遗传"],
  ["mucinous", "黏液"],
  ["baseball", "棒球"],
  ["swimming", "游泳"],
  ["scapular", "肩胛"],
  ["ablation", "消融"],
  ["diagnose", "诊断"],
  ["humeral", "肱骨"],
  ["fibrous", "纤维性"],
  ["control", "控制"],
  ["sensory", "感觉"],
  ["culture", "培养"],
  ["femoral", "股骨"],
  ["obesity", "肥胖"],
  ["minimus", "小"],
  ["triceps", "肱三头肌"],
  ["against", "抗"],
  ["gravity", "重力"],
  ["medical", "医学"],
  ["burning", "灼痛"],
  ["dancers", "舞者"],
  ["process", "过程"],
  ["segment", "节段"],
  ["density", "密度"],
  ["grading", "分级"],
  ["extreme", "极端"],
  ["descent", "下降"],
  ["basilar", "颅底"],
  ["aplasia", "发育不全"],
  ["contact", "接触"],
  ["profile", "轮廓"],
  ["adapted", "调整"],
  ["sarcoma", "肉瘤"],
  ["ossific", "骨化"],
  ["physeal", "骺板"],
  ["similar", "相似"],
  ["blister", "水疱"],
  ["sharing", "共享"],
  ["smoking", "吸烟"],
  ["concern", "关注"],
  ["styloid", "茎突"],
  ["overall", "总体"],
  ["phalanx", "指骨"],
  ["serpent", "蛇形"],
  ["thyroid", "甲状腺"],
  ["calcium", "钙"],
  ["jamming", "撞击"],
  ["migrate", "移位"],
  ["between", "之间"],
  ["players", "运动员"],
  ["bending", "弯曲"],
  ["walking", "行走"],
  ["seeding", "种植"],
  ["seizure", "癫痫"],
  ["release", "释放"],
  ["tubular", "小管"],
  ["tendons", "肌腱"],
  ["nodular", "结节"],
  ["locally", "局部"],
  ["ectopia", "异位"],
  ["refusal", "拒动"],
  ["bladder", "膀胱"],
  ["ectopic", "异位"],
  ["sourcil", "眉弓"],
  ["staging", "分期"],
  ["narrow", "狭窄"],
  ["return", "返回"],
  ["always", "总是"],
  ["formal", "正式"],
  ["global", "整体"],
  ["mobile", "可动"],
  ["bottom", "底部"],
  ["rocker", "摇椅"],
  ["stance", "站立"],
  ["medium", "中等"],
  ["larger", "更大"],
  ["absent", "缺失"],
  ["coiled", "卷曲"],
  ["simple", "简单"],
  ["pseudo", "假"],
  ["relief", "缓解"],
  ["second", "第二"],
  ["assess", "评估"],
  ["proven", "证实"],
  ["statin", "他汀"],
  ["marker", "标志物"],
  ["thecal", "硬膜"],
  ["source", "来源"],
  ["urgent", "紧急"],
  ["aspect", "方面"],
  ["mature", "成熟"],
  ["needed", "需要"],
  ["bridge", "桥接"],
  ["bowing", "弯曲"],
  ["gutter", "沟"],
  ["valgus", "外翻"],
  ["bruise", "瘀伤"],
  ["hernia", "疝"],
  ["lesser", "小"],
  ["gentle", "轻柔"],
  ["filled", "充填"],
  ["axilla", "腋窝"],
  ["acuity", "敏锐度"],
  ["accept", "可接受"],
  ["within", "内"],
  ["milder", "更轻"],
  ["danger", "危险"],
  ["behind", "后方"],
  ["guides", "指南"],
  ["workup", "检查"],
  ["rising", "上升"],
  ["patchy", "斑片"],
  ["rhabdo", "横纹肌溶解"],
  ["plexus", "丛"],
  ["months", "月"],
  ["disuse", "废用"],
  ["eyelid", "眼睑"],
  ["lipids", "脂质"],
  ["pelvic", "骨盆"],
  ["vermis", "蚓部"],
  ["fourth", "第四"],
  ["beaked", "鸟嘴样"],
  ["tectum", "顶盖"],
  ["collar", "颈托"],
  ["tetany", "手足搐搦"],
  ["analog", "类似物"],
  ["screws", "螺钉"],
  ["plicae", "皱襞"],
  ["gender", "性别"],
  ["resect", "切除"],
  ["failed", "失败"],
  ["joints", "关节"],
  ["frozen", "冻结"],
  ["bowtie", "领结样"],
  ["celery", "芹菜"],
  ["button", "纽扣"],
  ["pointe", "尖"],
  ["shoes", "鞋"],
  ["plate", "钢板"],
  ["prior", "既往"],
  ["minus", "负"],
  ["donor", "供体"],
  ["probe", "探针"],
  ["pubic", "耻骨"],
  ["stair", "楼梯"],
  ["speed", "速度"],
  ["labor", "劳动"],
  ["force", "力量"],
  ["sport", "运动"],
  ["mimic", "模拟"],
  ["bands", "带"],
  ["heads", "头"],
  ["cases", "病例"],
  ["plain", "平片"],
  ["urine", "尿"],
  ["group", "组"],
  ["shunt", "分流"],
  ["mouth", "口"],
  ["blood", "血"],
  ["motor", "运动"],
  ["solid", "实性"],
  ["clunk", "弹响"],
  ["shear", "剪切"],
  ["varus", "内翻"],
  ["tophi", "痛风石"],
  ["tumor", "肿瘤"],
  ["voids", "信号"],
  ["ramus", "支"],
  ["label", "标签"],
  ["press", "压"],
  ["tears", "撕裂"],
  ["sling", "吊带"],
  ["above", "上方"],
  ["minor", "轻微"],
  ["glass", "玻璃"],
  ["knife", "刀"],
  ["fight", "打斗"],
  ["buddy", "邻指"],
  ["blunt", "钝性"],
  ["drift", "漂移"],
  ["ovoid", "卵圆"],
  ["wider", "更宽"],
  ["great", "大"],
  ["talar", "距骨"],
  ["along", "沿"],
  ["signs", "征象"],
  ["score", "评分"],
  ["month", "月"],
  ["atlas", "寰椎"],
  ["hours", "小时"],
  ["dural", "硬膜"],
  ["false", "假"],
  ["valve", "瓣"],
  ["thick", "厚"],
  ["stalk", "杆"],
  ["point", "点"],
  ["inter", "间"],
  ["free", "游离"],
  ["ring", "环"],
  ["horn", "角"],
  ["peel", "剥离"],
  ["fist", "拳"],
  ["gait", "步态"],
  ["pure", "纯"],
  ["days", "天"],
  ["flex", "屈曲"],
  ["toes", "趾"],
  ["shoe", "鞋"],
  ["dark", "暗"],
  ["less", "更少"],
  ["axis", "枢椎"],
  ["time", "时间"],
  ["self", "自身"],
  ["jump", "跳跃"],
  ["slip", "滑移"],
  ["flow", "流空"],
  ["pull", "牵拉"],
  ["bear", "负重"],
  ["clue", "线索"],
  ["plan", "计划"],
  ["blow", "打击"],
  ["area", "区域"],
  ["mask", "掩蔽"],
  ["long", "长"],
  ["thin", "薄"],
  ["bite", "咬伤"],
  ["full", "完全"],
  ["main", "主要"],
  ["case", "病例"],
  ["shin", "胫"],
  ["film", "片"],
  ["drug", "药物"],
  ["cell", "细胞"],
  ["peak", "峰值"],
  ["urti", "上呼吸道感染"],
  ["dose", "剂量"],
  ["type", "类型"],
  ["pins", "钉"],
  ["situ", "原位"],
  ["demi", "半"],
  ["off", "台阶"],
  ["tip", "尖端"],
  ["end", "端"],
  ["toe", "趾"],
  ["run", "跑步"],
  ["key", "关键"],
  ["rim", "边缘"],
  ["sac", "囊"],
  ["row", "列"],
  ["oss", "骨化"],
  ["hug", "抱"],
  ["mid", "中段"],
  ["rib", "肋"],
  ["box", "盒"],
  ["pad", "垫"],
  ["lab", "实验室"],
  ["cm", "厘米"],
];
