/**
 * 通用英文 → 中文（非疾病专用缩写/人名/分型名）
 */
export const GENERAL_PHRASES = [
  ['stretching/strengthening program', '拉伸/强化训练方案'],
  ['quadriceps/hamstring stretching', '股四头肌/腘绳肌拉伸'],
  ['stretching/strengthening', '拉伸/强化训练'],
  ['FHL stretching', '拇长屈肌拉伸'],
  ['minimally invasive', '微创'],
  ['cost-effective', '经济有效'],
  ['physical therapy', '物理治疗'],
  ['activity modification', '活动调整'],
  ['protected weight bearing', '保护负重'],
  ['weight bearing', '负重'],
  ['needle lavage', '针吸冲洗'],
  ['US-guided', '超声引导'],
  ['US guided', '超声引导'],
  ['cloud sign', '云征'],
  ['cloud-like', '云样'],
  ['skeletal maturity', '骨骼成熟'],
  ['manual reduction', '手法复位'],
  ['nerve root', '神经根'],
  ['soft tissue', '软组织'],
  ['joint line', '关节线'],
  ['joint space', '关节间隙'],
  ['full thickness', '全层'],
  ['low signal', '低信号'],
  ['high signal', '高信号'],
  ['bone marrow', '骨髓'],
  ['stress fracture', '应力性骨折'],
  ['pathologic fracture', '病理性骨折'],
  ['avulsion fracture', '撕脱骨折'],
  ['occult fracture', '隐匿骨折'],
  ['fat pad', '脂肪垫'],
  ['double line sign', '双线征'],
  ['enter-exit sign', '进出神经征'],
  ['split fat sign', '脂肪分隔征'],
  ['bone destruction', '骨破坏'],
  ['periosteal reaction', '骨膜反应'],
  ['cartilage loss', '软骨丢失'],
  ['joint effusion', '关节积液'],
  ['spinal canal', '椎管'],
  ['disc space', '间盘间隙'],
  ['muscle belly', '肌腹'],
  ['tendon insertion', '肌腱止点'],
  ['follow-up', '随访'],
  ['follow up', '随访'],
  ['with contrast', '增强扫描'],
  ['without contrast', '平扫'],
  ['cross sectional', '横断面'],
  ['coronal plane', '冠状面'],
  ['axial plane', '轴位面'],
  ['sagittal plane', '矢状面'],
  ['conservative treatment', '保守治疗'],
  ['operative treatment', '手术治疗'],
  ['surgical excision', '手术切除'],
  ['wide resection', '广泛切除'],
  ['differential diagnosis', '鉴别诊断'],
  ['imaging findings', '影像表现'],
  ['clinical features', '临床特征'],
  ['natural history', '自然病程'],
  ['exercise program', '训练方案'],
  ['rehabilitation program', '康复方案'],
  ['treatment protocol', '治疗方案'],
  ['diagnostic tool', '诊断工具'],
  ['diagnostic test', '诊断试验'],
  ['persistent symptoms', '持续症状'],
  ['underlying disease', '基础疾病'],
  ['concurrent infection', '合并感染'],
  ['family history', '家族史'],
  ['calcific tendinitis', '钙化性肌腱炎'],
  ['rotator cuff tear', '肩袖撕裂'],
  ['labral tear', '盂唇撕裂'],
  ['meniscal tear', '半月板撕裂'],
  ['nerve entrapment', '神经卡压'],
  ['foot drop', '足下垂'],
  ['low back pain', '腰痛'],
  ['groin pain', '腹股沟痛'],
  ['at maturity', '至骨骼成熟'],
  ['on activity', '活动时'],
  ['during activity', '活动时'],
  ['after activity', '活动后'],
  ['ice pack', '冰敷'],
  ['pain relief', '止痛'],
  ['strength training', '力量训练'],
  ['home exercise', '家庭锻炼'],
  ['range of motion exercises', '活动度训练'],
  ['sports related', '运动相关'],
  ['occupation related', '职业相关'],
  ['poor prognosis', '预后差'],
  ['good prognosis', '预后好'],
  ['missed diagnosis', '漏诊'],
  ['early diagnosis', '早期诊断'],
  ['acute phase', '急性期'],
  ['chronic phase', '慢性期'],
  ['non union', '不愈合'],
  ['growth plate', '生长板'],
  ['bone age', '骨龄'],
  ['bone tumor', '骨肿瘤'],
  ['soft tissue mass', '软组织肿块'],
  ['soft tissue swelling', '软组织肿胀'],
  ['trigger finger', '扳机指'],
  ['carpal tunnel', '腕管'],
  ['subacromial injection', '肩峰下注射'],
  ['subacromial-subdeltoid', '肩峰下-三角肌下'],
  ['Relative rest', '相对休息'],
  ['relative rest', '相对休息'],
  ['knee pad', '膝垫'],
  ['kneeling activities', '跪姿活动'],
  ["Jumper's knee", '跳跃膝'],
  ['no apophysis', '无骨骺'],
  ['resisted extension', '抗阻伸展'],
  ['injection guidance', '注射引导'],
  ['needle guidance', '穿刺引导']
];

export const GENERAL_WORDS = [
  ['program', '方案'],
  ['stretching', '拉伸'],
  ['strengthening', '强化训练'],
  ['effective', '有效'],
  ['observe', '观察'],
  ['routine', '常规'],
  ['asymptomatic', '无症状'],
  ['refractory', '难治性'],
  ['symptoms', '症状'],
  ['barbotage', '穿刺冲洗'],
  ['lavage', '冲洗'],
  ['neurectomy', '神经切除'],
  ['mobilization', '活动训练'],
  ['Ice', '冰敷'],
  ['ice', '冰敷'],
  ['disease', '疾病'],
  ['operative', '手术'],
  ['patient', '患者'],
  ['patients', '患者'],
  ['advanced', '进展期'],
  ['functional', '功能'],
  ['infection', '感染'],
  ['deficit', '功能障碍'],
  ['insertion', '止点'],
  ['attachment', '附着点'],
  ['underlying', '基础'],
  ['congenital', '先天性'],
  ['maturity', '成熟'],
  ['growth', '生长'],
  ['resorption', '吸收'],
  ['abductor', '外展肌'],
  ['transfer', '转位'],
  ['degeneration', '变性'],
  ['massive', '大块'],
  ['migration', '迁移'],
  ['palpable', '可触及'],
  ['factor', '因素'],
  ['factors', '因素'],
  ['graft', '移植物'],
  ['specific', '特定'],
  ['occult', '隐匿'],
  ['transverse', '横'],
  ['ossicle', '小骨块'],
  ['territory', '区域'],
  ['occupation', '职业'],
  ['separation', '分离'],
  ['guided', '引导'],
  ['finding', '表现'],
  ['findings', '表现'],
  ['belly', '腹'],
  ['stiffness', '僵硬'],
  ['systemic', '全身'],
  ['treat', '治疗'],
  ['aspiration', '抽吸'],
  ['wear', '磨损'],
  ['protected', '保护性'],
  ['greater', '较大'],
  ['protocol', '方案'],
  ['contour', '轮廓'],
  ['visible', '可见'],
  ['persistent', '持续'],
  ['manual', '手法'],
  ['forearm', '前臂'],
  ['planning', '规划'],
  ['interface', '界面'],
  ['contracture', '挛缩'],
  ['cloud', '云样'],
  ['central', '中央'],
  ['premature', '过早'],
  ['family', '家族'],
  ['insufficiency', '功能不全'],
  ['subtle', '细微'],
  ['familial', '家族性'],
  ['linear', '线样'],
  ['mixed', '混合'],
  ['wedge', '楔形'],
  ['rarely', '少见'],
  ['microtrauma', '微损伤'],
  ['volume', '容量'],
  ['triad', '三联征'],
  ['quality', '质量'],
  ['strength', '强度'],
  ['middle', '中间'],
  ['timing', '时机'],
  ['missed', '漏诊'],
  ['severity', '严重程度'],
  ['prognosis', '预后'],
  ['assessment', '评估'],
  ['procedure', '操作'],
  ['removal', '去除'],
  ['immobilization', '固定'],
  ['alcohol', '酒精'],
  ['concurrent', '合并'],
  ['renal', '肾'],
  ['status', '状态'],
  ['without', '无'],
  ['lipid', '脂质'],
  ['immature', '未成熟'],
  ['acquired', '获得性'],
  ['union', '愈合'],
  ['sports', '运动'],
  ['platform', '平台'],
  ['index', '指数'],
  ['bearing', '负重'],
  ['incomplete', '不完全'],
  ['resection', '切除'],
  ['adult', '成人'],
  ['gap', '间隙'],
  ['atrophy', '萎缩'],
  ['apophysitis', '骨骺炎'],
  ['tubercle', '结节'],
  ['calcific', '钙化性'],
  ['plantarflexion', '跖屈'],
  ['horizontal', '水平'],
  ['plane', '面'],
  ['chest', '胸'],
  ['metatarsal', '跖骨'],
  ['paraspinal', '椎旁'],
  ['arthroplasty', '置换术'],
  ['synostosis', '骨性连接'],
  ['spinal', '脊柱'],
  ['discoid', '盘状'],
  ['mucoid', '黏液样'],
  ['pannus', '血管翳'],
  ['osteolysis', '骨溶解'],
  ['discogenic', '间盘源性'],
  ['discitis', '间盘炎'],
  ['septic', '化脓性'],
  ['gouty', '痛风性'],
  ['tophus', '痛风石'],
  ['deposition', '沉积'],
  ['antibiotic', '抗生素'],
  ['tool', '工具'],
  ['trial', '试验'],
  ['alone', '单独'],
  ['often', '常'],
  ['other', '其他'],
  ['rare', '罕见'],
  ['typical', '典型'],
  ['progressive', '进行性'],
  ['sudden', '突发'],
  ['gradual', '逐渐'],
  ['recurrent', '反复'],
  ['transient', '短暂'],
  ['partial', '部分'],
  ['complete', '完全'],
  ['fragmentation', '碎裂'],
  ['displacement', '移位'],
  ['angulation', '成角'],
  ['reduction', '复位'],
  ['excision', '切除'],
  ['debridement', '清理'],
  ['biopsy', '活检'],
  ['injection', '注射'],
  ['therapy', '治疗'],
  ['treatment', '治疗'],
  ['management', '处理'],
  ['evaluation', '评估'],
  ['monitoring', '监测'],
  ['complication', '并发症'],
  ['complications', '并发症'],
  ['recovery', '恢复'],
  ['healing', '愈合'],
  ['resolution', '消退'],
  ['failure', '失败'],
  ['response', '反应'],
  ['indication', '指征'],
  ['alternative', '替代'],
  ['option', '选择'],
  ['options', '选择'],
  ['strategy', '策略'],
  ['approach', '方法'],
  ['method', '方法'],
  ['technique', '技术'],
  ['enhancement', '强化'],
  ['intensity', '强度'],
  ['appearance', '表现'],
  ['morphology', '形态'],
  ['location', '部位'],
  ['distribution', '分布'],
  ['extent', '范围'],
  ['margin', '边缘'],
  ['border', '边界'],
  ['cortical', '皮质'],
  ['trabecular', '骨小梁'],
  ['medullary', '髓内'],
  ['periarticular', '关节周围'],
  ['intramuscular', '肌内'],
  ['intermuscular', '肌间'],
  ['intramedullary', '髓内'],
  ['periosteal', '骨膜'],
  ['cartilaginous', '软骨性'],
  ['osseous', '骨性'],
  ['lytic', '溶骨性'],
  ['blastic', '成骨性'],
  ['sclerotic', '硬化性'],
  ['lucent', '透亮'],
  ['radiolucent', '透射'],
  ['radiopaque', '不透射'],
  ['isointense', '等信号'],
  ['heterogeneous', '不均匀'],
  ['homogeneous', '均匀'],
  ['defined', '界清'],
  ['infiltrative', '浸润性'],
  ['expansile', '膨胀性'],
  ['destructive', '破坏性'],
  ['aggressive', '侵袭性'],
  ['benign', '良性'],
  ['malignant', '恶性'],
  ['metastatic', '转移性'],
  ['recurrence', '复发'],
  ['metastasis', '转移'],
  ['hemorrhage', '出血'],
  ['hematoma', '血肿'],
  ['effusion', '积液'],
  ['synovitis', '滑膜炎'],
  ['tenosynovitis', '腱鞘炎'],
  ['bursitis', '滑囊炎'],
  ['osteomyelitis', '骨髓炎'],
  ['cellulitis', '蜂窝织炎'],
  ['abscess', '脓肿'],
  ['granuloma', '肉芽肿'],
  ['plaque', '斑块'],
  ['stricture', '狭窄'],
  ['obstruction', '梗阻'],
  ['impingement', '撞击'],
  ['instability', '不稳'],
  ['subluxation', '半脱位'],
  ['dislocation', '脱位'],
  ['contusion', '挫伤'],
  ['sprain', '扭伤'],
  ['strain', '拉伤'],
  ['rupture', '断裂'],
  ['laceration', '裂伤'],
  ['hemarthrosis', '血关节'],
  ['tenderness', '压痛'],
  ['weakness', '无力'],
  ['numbness', '麻木'],
  ['paresthesia', '感觉异常'],
  ['paresis', '轻瘫'],
  ['claudication', '跛行'],
  ['deformity', '畸形'],
  ['redness', '发红'],
  ['warmth', '发热感'],
  ['fever', '发热'],
  ['history', '病史'],
  ['training', '训练'],
  ['exercise', '锻炼'],
  ['activity', '活动'],
  ['athlete', '运动员'],
  ['athletes', '运动员'],
  ['adolescent', '青少年'],
  ['elderly', '老年'],
  ['dominant', '优势侧'],
  ['nondominant', '非优势侧'],
  ['contralateral', '对侧'],
  ['ipsilateral', '同侧'],
  ['comparison', '对比'],
  ['baseline', '基线'],
  ['screening', '筛查'],
  ['monitor', '监测'],
  ['exclude', '排除'],
  ['confirm', '确认'],
  ['suggest', '提示'],
  ['indicate', '表明'],
  ['support', '支持'],
  ['consistent', '符合'],
  ['compatible', '相符'],
  ['possible', '可能'],
  ['probable', '很可能'],
  ['unlikely', '不太可能'],
  ['definite', '明确'],
  ['definitive', '确诊'],
  ['suspicious', '可疑'],
  ['equivocal', '不确定'],
  ['negative', '阴性'],
  ['positive', '阳性'],
  ['abnormal', '异常'],
  ['anomaly', '异常'],
  ['artifact', '伪影'],
  ['motion', '运动'],
  ['breathing', '呼吸'],
  ['metal', '金属'],
  ['hardware', '内固定'],
  ['implant', '植入物'],
  ['prosthesis', '假体'],
  ['screw', '螺钉'],
  ['wire', '钢丝'],
  ['anchor', '锚钉'],
  ['suture', '缝合'],
  ['bandage', '敷料'],
  ['cast', '石膏'],
  ['splint', '夹板'],
  ['brace', '支具'],
  ['emergency', '急诊'],
  ['elective', '择期'],
  ['outpatient', '门诊'],
  ['inpatient', '住院'],
  ['multidisciplinary', '多学科'],
  ['surgeon', '外科医生'],
  ['radiologist', '放射科医生'],
  ['physician', '医生'],
  ['therapist', '治疗师'],
  ['education', '宣教'],
  ['counseling', '咨询'],
  ['advice', '建议'],
  ['recommended', '推荐'],
  ['preferred', '首选'],
  ['surveillance', '监测'],
  ['avoid', '避免'],
  ['prevent', '预防'],
  ['reduce', '减少'],
  ['improve', '改善'],
  ['worsen', '加重'],
  ['accelerate', '加速'],
  ['prolong', '延长'],
  ['shorten', '缩短'],
  ['maintain', '维持'],
  ['preserve', '保留'],
  ['restore', '恢复'],
  ['reconstruct', '重建'],
  ['replace', '置换'],
  ['remove', '去除'],
  ['drain', '引流'],
  ['irrigate', '冲洗'],
  ['visualize', '显示'],
  ['demonstrate', '显示'],
  ['reveal', '揭示'],
  ['detect', '检出'],
  ['identify', '识别'],
  ['recognize', '识别'],
  ['characterize', '表征'],
  ['quantify', '定量'],
  ['measure', '测量'],
  ['calculate', '计算'],
  ['estimate', '估计'],
  ['compare', '比较'],
  ['integrate', '整合'],
  ['combine', '联合'],
  ['include', '包括'],
  ['unless', '除非'],
  ['before', '之前'],
  ['after', '之后'],
  ['during', '期间'],
  ['until', '直到'],
  ['because', '因为'],
  ['therefore', '因此'],
  ['however', '然而'],
  ['although', '虽然'],
  ['despite', '尽管'],
  ['especially', '尤其'],
  ['particularly', '尤其'],
  ['mainly', '主要'],
  ['mostly', '多数'],
  ['usually', '通常'],
  ['typically', '通常'],
  ['generally', '一般'],
  ['commonly', '常见'],
  ['occasionally', '偶尔'],
  ['sometimes', '有时'],
  ['should', '应'],
  ['require', '需要'],
  ['requires', '需要'],
  ['required', '需要'],
  ['useful', '有用'],
  ['helpful', '有帮助'],
  ['appropriate', '适当'],
  ['insufficient', '不足'],
  ['inadequate', '不足'],
  ['subscap', '肩胛下肌'],
  ['tenodesis', '肌腱固定术'],
  ['deltoid', '三角肌'],
  ['quadrilateral', '四边形'],
  ['quad', '股四头肌'],
  ['hamstring', '腘绳肌'],
  ['quadriceps', '股四头肌'],
  ['plantaris', '跖肌'],
  ['adductor', '内收肌'],
  ['flexor', '屈肌'],
  ['extensor', '伸肌'],
  ['rotator', '旋转'],
  ['labral', '盂唇'],
  ['meniscal', '半月板'],
  ['ligament', '韧带'],
  ['tendon', '肌腱'],
  ['vessel', '血管'],
  ['artery', '动脉'],
  ['vein', '静脉'],
  ['synovium', '滑膜'],
  ['synovial', '滑膜'],
  ['bursa', '滑囊'],
  ['fascia', '筋膜'],
  ['physis', '生长板'],
  ['epiphysis', '骨骺'],
  ['metaphysis', '干骺端'],
  ['diaphysis', '骨干'],
  ['condyle', '髁'],
  ['plateau', '平台'],
  ['trochlea', '滑车'],
  ['notch', '切迹'],
  ['fossa', '窝'],
  ['groove', '沟'],
  ['canal', '管'],
  ['foramen', '孔'],
  ['meatus', '道'],
  ['sinus', '窦'],
  ['cavity', '腔'],
  ['compartment', '筋膜室'],
  ['sheath', '鞘'],
  ['capsule', '囊'],
  ['membrane', '膜'],
  ['minimally', '微创'],
  ['invasive', '侵入性'],
  ['modification', '调整'],
  ['modifications', '调整'],
  ['related', '相关'],
  ['weightlifter', '举重运动员'],
  ['continuity', '连续性'],
  ['ecchymosis', '瘀斑'],
  ['bursal', '滑囊'],
  ['multi', '多'],
  ['click', '弹响'],
  ['hook', '钩'],
  ['blade', '叶'],
  ['wound', '伤口'],
  ['split', '分裂'],
  ['calf', '小腿'],
  ['arm', '臂'],
  ['angle', '角度'],
  ['calcified', '钙化'],
  ['skeletal', '骨骼'],
  ['target', '靶'],
  ['burst', '爆裂'],
  ['reverse', '反向'],
  ['ancient', '陈旧'],
  ['engaging', '嵌合'],
  ['desmoid', 'Desmoid'],
  ['rickets', '佝偻病'],
  ['third', '第三'],
  ['web', '蹼'],
  ['bodies', '体'],
  ['total', '全'],
  ['view', '位'],
  ['load', '负荷'],
  ['cross', '交叉'],
  ['site', '部位'],
  ['change', '改变'],
  ['enter', '进入'],
  ['exit', '退出'],
  ['true', '真'],
  ['like', '样'],
  ['use', '使用'],
  ['age', '年龄'],
  ['young', '青年'],
  ['child', '儿童'],
  ['children', '儿童'],
  ['male', '男性'],
  ['female', '女性'],
  ['subacromial', '肩峰下'],
  ['subdeltoid', '三角肌下'],
  ['shadowing', '声影'],
  ['deposit', '沉积'],
  ['guidance', '引导'],
  ['integrity', '完整性'],
  ['Relative', '相对'],
  ['relative', '相对'],
  ['kneeling', '跪姿'],
  ['resisted', '抗阻'],
  ['apophysis', '骨骺'],
  ['distension', '膨胀'],
  ['dense', '致密'],
  ['calcification', '钙化'],
  ['reaction', '反应'],
  ['extension', '伸展'],
  ['flexion', '屈曲'],
  ['distal', '远端'],
  ['proximal', '近端'],
  ['posterior', '后'],
  ['anterior', '前'],
  ['lateral', '外侧'],
  ['medial', '内侧'],
  ['pre', '前'],
  ['post', '后'],
  ['over', '过度'],
  ['weight', '负重'],
  ['upper', '上'],
  ['lower', '下'],
  ['core', '核心'],
  ['axial', '轴位'],
  ['carpal', '腕'],
  ['epidural', '硬膜外'],
  ['stenosis', '狭窄'],
  ['ratio', '比值'],
  ['stump', '残端'],
  ['focus', '关注'],
  ['cortex', '皮质'],
  ['weight', '重量'],
  ['distance', '距离'],
  ['recess', '隐窝'],
  ['acetabular', '髋臼'],
  ['vertebra', '椎体'],
  ['neuroma', '神经瘤'],
  ['ossified', '骨化'],
  ['retropulsion', '后移'],
  ['mortise', '榫眼'],
  ['impaction', '嵌插'],
  ['crescent', '新月形'],
  ['sternal', '胸骨'],
  ['upper', '上方'],
  ['desmoid', 'Desmoid'],
  ['pars', 'Pars'],
  ['apophysis', '骨骺'],
  ['odontoideum', 'Odontoideum'],
  ['charcot', 'Charcot'],
  ['chondrocalcinosis', '软骨钙化'],
  ['subperiosteal', '骨膜下'],
  ['hydrocephalus', '脑积水'],
  ['saucerization', '碟形切除'],
  ['dediff', '去分化'],
  ['radiocapitellar', '桡骨小头'],
  ['canale', 'Canale'],
  ['nidus', '巢'],
  ['neuroma', '神经瘤'],
  ['activities', '活动'],
  ['activity', '活动'],
  ['rest', '休息'],
  ['pain', '疼痛'],
  ['adult', '成人'],
  ['boys', '男孩'],
  ['girls', '女孩'],
  ['basketball', '篮球'],
  ['soccer', '足球'],
  ['volleyball', '排球'],
  ['jumping', '跳跃'],
  ['running', '跑步'],
  ['inflammation', '炎症'],
  ['repetitive', '重复性'],
  ['traction', '牵拉'],
  ['prominence', '隆起'],
  ['prominent', '突出'],
  ['tender', '压痛'],
  ['resolve', '缓解'],
  ['resolves', '缓解'],
  ['fragmentation', '碎裂'],
  ['fragment', '碎片'],
  ['swelling', '肿胀'],
  ['normal', '正常'],
  ['variant', '变异'],
  ['active', '活动期'],
  ['radiographic', '影像'],
  ['radiograph', 'X线片']
];
